version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    image: mongo
    links:
      - mongodb

    volumes:
      - ./data:/initial-data

    command:
      "mongoimport --host mongo --port 27017 --db snoicd-codex --mode upsert --collection internal-knowledge-base --file /initial-data/internal-knoledge-base-en.json --jsonArray"

    links:
      - mongo
